stages:
  - first
  - second
  - third

print_first:
  stage: first
  tags:
    - cicd
  only:
    - master
  script:
    - echo "Hello, first"

print_second:
  stage: second
  tags:
    - cicd
  only:
    - master
  script:
    - echo "Hello, second"

print_third:
  stage: third
  tags:
    - cicd
  only:
    - master
  script:
    - echo "Hello, third"
