stages:
  - build
  - deploy

variables:
  REGISTRY: "registry.gitlab.com/anton4ik8374/cicd_docker_laravel"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

app_build:
  stage: build
  tags:
    - build
  only:
    - master
  script:
    - docker build --build-arg NODE_ENV="dev" -t "$REGISTRY/dev/app:$CI_COMMIT_SHA" -f ./_docker/app/Dockerfile .
    - docker push "$REGISTRY/dev/app:$CI_COMMIT_SHA"

